# Generated by Django 5.2.1 on 2025-05-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_services_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='contact',
            new_name='content',
        ),
    ]
