# Generated by Django 5.2.1 on 2025-05-13 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 19, 57, 32, 816455, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
